# toml Directive
# [[Directives]]
# ID="hired.TOMlUser"
# [Directives.Config]
# Source        ="appdata/users.static.toml"
# ProfileFields =["field1","field2"]
# ServePassword =true
# ServeStatus   =true
# ServeAccounts =true
# ServeRoles    =true
# ServeTerm     =true
# ServeProfile  =true
# HashMode="md5"

# # herbsession Directive
# [[Directives]]
# ID="hired.HerbSession"
# [Directives.Config]
# DriverName = "cache"
# TokenLifetime = "1h"
# TokenMaxLifetime = "168h"
# TokenContextName = "token"
# CookieName = "herb-go-Members"
# CookiePath = "/"
# CookieSecure = false
# UpdateActiveIntervalInSecond = 100
# TokenLength = 32
# [Directives.Config.Cache]
# Driver = "syncmapcache"
# TTL = 3600

# # memactives Directive
# [[Directives]]
# ID="hired.MemActives"
# [Directives.Config]
# [Directives.Config.Durations]
# "web"="60m"
# memactives Directive

# [[Directives]]
# ID="hired.RedisActives"
# [Directives.Config]
# Prefix="actives"
# Network="tcp"
# Address="127.0.0.1:6379"
# Password="password"
# Db=1
# ConnectTimeoutInSecond=60
# ReadTimeoutInSecond=60
# WriteTimeoutInSecon=60
# MaxIdle=100
# MaxAlive=200
# IdleTimeoutInSecond=60
# [Directives.Config.Durations]
# "web"="20s"

# # payload created time Directive
# [[Directives]]
# ID="hired.PayloadLogintime"

# # payload http ip Directive
# [[Directives]]
# ID="hired.PayloadHTTPIp"

# # memactives Directive
# [[Directives]]
# ID="hired.UserCache"
# [Directives.Config]
# PrefixStatus="status"
# PrefixTerm="term"
# PrefixAccount="account"
# PrefixRole="role"
# PrefixProfile="profile"
# [Directives.Config.Cache.Preset]
# TTL=1800
# Namspace=""
# Prefix=""
# [Directives.Config.Cache.Storage]
# ID=""
# [Directives.Config.Cache.Storage.Engine]
# VersionTTL=3600
# [Directives.Config.Cache.Storage.Engine.Cache]
# Driver="freecache"
# [Directives.Config.Cache.Storage.Engine.Cache.Config]
# Size=50000000
# [Directives.Config.Cache.Storage.Engine.VersionStore]
# Driver="inmemory"
# [Directives.Config.Cache.Storage.Engine.VersionStore.Config]